Updates file template generator service
TripalCultivate/TripalCultivate-Phenotypes pull request #133
Opened 2024-12-20 17:56 UTC by reynoldtan

**Issue #124** Automated test needed for describeUploadFileFormat().

## Motivation
This PR updates the template generator service and automated test to accommodate customization of file extension of the generated template file. The previous version supports a single file extension and is hard-coded into the logic of the class. In addition, an unused variable $notes in https://github.com/TripalCultivate/TripalCultivate-Phenotypes/blob/3d934ca9215e046bd890e00cce6f2388cd19445f/trpcultivate_phenotypes/src/Plugin/TripalImporter/TripalCultivatePhenotypesTraitsImporter.php#L1488 was not implemented but is now added into the header information section (see image below).

<img width="944" alt="image" src="https://github.com/user-attachments/assets/2e8821ad-282e-41db-b806-3da47cd23cd0" />

## What does this PR do?
*Please describe each things this PR does. For example, a PR may 1) solve a specific bug, 2) create an automated test to ensure it doesn't return.*

1. Display additional notes in the headers information section of the Importer form.
2. Replace the static file extension by improving the logic of determining the supported file types.
3. Reference static variables in validator base and validator file types to establish MIME type and delimiter.
4. Upgrade automated test.

## Testing

### Automated Testing
*Please describe each automated test this PR creates and provide a list of the assertions it makes using casual language.*
*Do not just say things like "asserts the array is not empty" but rather say "Ensures that the return value of method X with these parameters is not an empty array".*

ClassName->testTemplateGeneratorService()
- file_types annotation definition with single item - tsv.
- file_types annotation definition with multiple items but only the first item is preferred.
- A file type (txt - text/plain) where the mapping of delimiter contains multiple characters but only the first item is selected.

For every test case, the template generator is check to:
1. It creates the file uri to the template file.
2. The template file is stored in the configured directory for template files.
3. Filename is a combination of the plugin id, a string, current user username.
4. Filename contains the plugin id.
5. Filename contains the username.
6. File extension is the expected file extension.
7. The header row matches the headers array if it was encoded as string using the delimiter.
8. Separating the header row string should match the raw headers array.

### Manual Testing
*Describe in detail how someone should manually test this functionality.*
*Make sure to include whether they need to build a docker from scratch, create any records, etc.*

1. Switch to g2.124-describeUploadFileFormat
2. In a fully setup site, paste the code below in your site/devel/php
```
$template_generator = \Drupal::service('trpcultivate_phenotypes.template_generator');

$column_headers = [
  'Header A',
  'Header B',
  'Header C'
];

$importer_id = 'my-importer';

$file_extensions = [
  'tsv',
  'csv'
];

$l = $template_generator->generateFile($importer_id, $column_headers, $file_extensions);

dpm($l);

```
3. Copy the link and paste in the location bar in another browser window.
<img width="723" alt="image" src="https://github.com/user-attachments/assets/ed4256e2-2c2d-48ff-a56a-0801db5d3a64" />
4. Append the uri with the host.
localhost/site/default/file....
5. Click enter and save file when prompted. Adjust parameters to test.

2025-01-14 22:13 UTC, carolyncaron requested changes
Overall, this is looking great! I made some minor suggestions in comments/documentation but the code overall looks good to me 👍 

For manual testing, the thing that stood out right away was the following deprecation notice:
![Screenshot 2025-01-14 at 4 02 50 PM](https://github.com/user-attachments/assets/3d39f880-13fe-4293-a6f5-52faeb60125a)
We've discussed this a bit with Lacey and realized that fixing this may be out of the scope of this PR. But I'm documenting it here as something that popped up while testing. The error also shows up on the Traits Importer page as well 🙈 

When I switch the order of tsv and csv in the example PHP Execute code, it generates a template with comma separated headers as expected. But, the help text on line 2 tells the user to use the TAB KEY for delimiting their file, which isn't ideal 😢 
![Screenshot 2025-01-14 at 4 07 11 PM](https://github.com/user-attachments/assets/370b5bfa-7ebb-487d-95cb-752365468d74)

I did confirm that downloading a template file from the Traits Importer page still works as expected 👍

2025-01-14 22:13 UTC, carolyncaron commented on trpcultivate_phenotypes/src/Plugin/TripalImporter/TripalCultivatePhenotypesTraitsImporter.php
>      methods), then you should have one line per collection method with the trait repeated.');
```suggestion
    methods), then you should have one line per collection method with the trait name/description repeated.');
```

2025-01-14 22:13 UTC, carolyncaron commented on trpcultivate_phenotypes/src/Service/TripalCultivatePhenotypesFileTemplateService.php
> +   *   multiple file type values were provided.
```suggestion
   *   NOTE: Only the first item is used as the primary file extension, in case
   *   of multiple file type values were provided.
```

2025-01-14 22:13 UTC, carolyncaron commented on trpcultivate_phenotypes/src/Service/TripalCultivatePhenotypesFileTemplateService.php
> +   *   Abosolute path to the template file.
```suggestion
   *   The absolute path to the generated template file.
```

2025-01-14 22:13 UTC, carolyncaron commented on trpcultivate_phenotypes/src/Service/TripalCultivatePhenotypesFileTemplateService.php
> +   *   The file extension of the template file. This is taken from the the
```suggestion
   *   The file extension of the template file. This is taken from the
```

2025-01-14 22:13 UTC, carolyncaron commented on trpcultivate_phenotypes/src/Plugin/TripalImporter/TripalCultivatePhenotypesTraitsImporter.php
>     * {@inheritdoc}
The inherited doc is located in TripalImporterBase but is quite minimal and I think this function has added a lot. Might it be better to add our own documentation rather than inheriting?

2025-01-14 22:13 UTC, carolyncaron commented on trpcultivate_phenotypes/src/Plugin/TripalImporter/TripalCultivatePhenotypesTraitsImporter.php
> +   * @see src/TripalCultivateValidator/ValidatorTraits/FileTypes.php
I don't know what the standards are for @see in doc blocks, but it would be helpful if it was explained briefly why I should see those 2 classes. :)

2025-01-14 22:13 UTC, carolyncaron commented on trpcultivate_phenotypes/tests/src/Kernel/ServiceTemplateGeneratorTest.php
> +   *     - 'file_content': the expected content (header row) of the file.
```suggestion
   *     - 'filename': the expected filename of the template file.
   *     - 'extension': the expected file extension of the template file.
   *     - 'delimiter': the expected delimiter used to encode the header row.
   *     - 'header_row': the expected content (header row) of the file.
```

2025-01-14 22:13 UTC, carolyncaron commented on trpcultivate_phenotypes/tests/src/Kernel/ServiceTemplateGeneratorTest.php
> +   *     - 'file_content': the expected content (header row) of the file.
I copy and pasted from the data provider doc since this section appeared to have gone out of sync.

2025-01-14 22:13 UTC, carolyncaron commented on trpcultivate_phenotypes/tests/src/Kernel/ServiceTemplateGeneratorTest.php
> +    // Assert that a file has been created in the the configured directory
```suggestion
    // Assert that a file has been created in the configured directory
```

2025-01-14 22:42 UTC, reynoldtan commented on trpcultivate_phenotypes/src/Service/TripalCultivatePhenotypesFileTemplateService.php
> +   *   Abosolute path to the template file.
This appears to be incorrect, from the manual test, the output is a relative path.

2025-01-14 22:46 UTC, reynoldtan commented on trpcultivate_phenotypes/src/Plugin/TripalImporter/TripalCultivatePhenotypesTraitsImporter.php
> +   * @see src/TripalCultivateValidator/ValidatorTraits/FileTypes.php
According to PROBLEMS tab, @see is a path to file, any @see with a text (to describe or other purpose) triggers a problem.

<img width="674" alt="image" src="https://github.com/user-attachments/assets/19df5411-166a-4953-b590-3e8be1b5a083" />

Now I realized that it should be in this method
https://github.com/TripalCultivate/TripalCultivate-Phenotypes/blob/56dfa0c771723cebe9fc6bd3184e1ee525c1f168/trpcultivate_phenotypes/src/Service/TripalCultivatePhenotypesFileTemplateService.php#L72

as reference regarding the mapping variables used then there is no need to explain. Good catch!

2025-01-15 15:36 UTC, reynoldtan commented
I found the deprecation notice in the official PHP website

https://www.php.net/manual/en/language.oop5.traits.php

![image](https://github.com/user-attachments/assets/2d17f14b-04b4-42f5-8fec-b20d40a245ef)

It looks like we need to access the mapping property using a getter method ie.

```
trait FileTypes {
  ...
  public static array $extension_to_mime_mapping = [
    'tsv' => ['text/tab-separated-values'],
    'csv' => ['text/csv'],
    'txt' => ['text/plain'],
  ];


  public static function getExtensionToMIME() {
    return self::$extension_to_mime_mapping;
  }

 ...

FileTypes::getExtensionToMIME();

instead of
FileTypes::$extension_to_mime_mapping; // Deprecated PHP 8.1

```

2025-01-15 16:11 UTC, carolyncaron commented on trpcultivate_phenotypes/src/Service/TripalCultivatePhenotypesFileTemplateService.php
> +   *   Abosolute path to the template file.
Oops, at least now we've been made aware of it!

2025-01-15 16:13 UTC, carolyncaron commented on trpcultivate_phenotypes/src/Plugin/TripalImporter/TripalCultivatePhenotypesTraitsImporter.php
> +   * @see src/TripalCultivateValidator/ValidatorTraits/FileTypes.php
Ahh, makes sense! For the future though, you could just add a sentence or two above the @see tags describing why they're needed, not necessarily on the @see line itself

2025-01-15 17:15 UTC, reynoldtan commented on trpcultivate_phenotypes/src/Service/TripalCultivatePhenotypesFileTemplateService.php
> +   *   Abosolute path to the template file.
I updated to indicate a relative path.

2025-01-15 17:16 UTC, reynoldtan commented on trpcultivate_phenotypes/src/Plugin/TripalImporter/TripalCultivatePhenotypesTraitsImporter.php
>     * {@inheritdoc}
I expanded the inheritdoc with references

2025-01-15 17:19 UTC, reynoldtan commented on trpcultivate_phenotypes/src/Plugin/TripalImporter/TripalCultivatePhenotypesTraitsImporter.php
> +   * @see src/TripalCultivateValidator/ValidatorTraits/FileTypes.php
it is serous about leaving the @see alone 😸 
![image](https://github.com/user-attachments/assets/92254f6a-4b4e-4d7d-8788-52b31a093332)

2025-01-15 22:18 UTC, laceysanderson requested changes
This PR looks mostly good :-) I just have a number of suggestions regarding the docblock for the describeUploadFormat.

2025-01-15 22:18 UTC, laceysanderson commented on trpcultivate_phenotypes/src/Plugin/TripalImporter/TripalCultivatePhenotypesTraitsImporter.php
> +   * @see Tripal\src\TripalImporter\TripalImporterBase.php
This should be the namespaced class and should point to the particular method.

```suggestion
   * @see Drupal\tripal\TripalImporter\TripalImporterBase::describeUploadFileFormat()
```

2025-01-15 22:18 UTC, laceysanderson commented on trpcultivate_phenotypes/src/Plugin/TripalImporter/TripalCultivatePhenotypesTraitsImporter.php
> +   * Provide a more informative description about the template file.
This feels more narrow then this method actually is. What about

```suggestion
   * Describe the upload format including column descriptions + template file.
```

2025-01-15 22:18 UTC, laceysanderson commented on trpcultivate_phenotypes/src/Plugin/TripalImporter/TripalCultivatePhenotypesTraitsImporter.php
> +   * to contain all headers required.
This could be reworded to be more clear and to make the connection between the twig file and the mentioned theme.

```suggestion
   * All relevant information relating to expected column headers and usage
   * notes are laid out using the theme 'importer_header'. This is rendered
   * using the referenced TWIG file below.
   *
   * A template geneartor service is utilized to provide a downloadable file
   * template, pre-configured to contain all headers required. The link to
   * this template file is also formatted using the theme 'importer_header'.
```

2025-01-15 22:18 UTC, laceysanderson commented on trpcultivate_phenotypes/src/Plugin/TripalImporter/TripalCultivatePhenotypesTraitsImporter.php
> +   *
Since you didn't use the inheritdoc, we need to redocument the return value.

```suggestion
   *
   * @return string
   *   The fully rendered HTML string produced by the 'importer_header' theme
   *   with the pertinent variables supplied by this method.
   *
```

2025-01-15 22:22 UTC, laceysanderson reviewed
Code coverage of the service is 100% however, there is no coverage for the describeUploadFormat() method in the importer...

2025-01-16 20:45 UTC, laceysanderson approved these changes, later dismissed
This all looks good to me now + thanks to the additional test we now have 100% coverage on both the template generator and the describeUploadFileFormat() method in the Trait Importer.

2025-01-17 18:13 UTC, carolyncaron commented on trpcultivate_phenotypes/src/Plugin/TripalImporter/TripalCultivatePhenotypesTraitsImporter.php
> +   * @see src/TripalCultivateValidator/ValidatorTraits/FileTypes.php
I think that expanding the docblock above describeUploadFileFormat() definitely helps in giving context as to why the current 2 files are listed, so I'll mark this as resolved 👍

2025-01-17 20:23 UTC, carolyncaron approved these changes, later dismissed
For the deprecation notice, it ended up being a really easy fix in commit [f9f45bd](https://github.com/TripalCultivate/TripalCultivate-Phenotypes/pull/133/commits/f9f45bd8db01ee1992eb36aecabc2d562100e161)

After looking into it further, the deprecation was not fixed by the addition of `use FileTypes;` alone, because `FileTypes::$extension_to_mime_mapping` still uses the trait version of the static variable. So changing it to `self` removed the notice because it now uses the inherited version of the static variable.

That said, we should still look into migrating static properties and methods to their own generic class in the future to make them more accessible to all plugins and services. This will make more sense to tackle after we migrate a lot of our validator code to TripalCultivate Base (see issue https://github.com/TripalCultivate/TripalCultivate/issues/36).

2025-01-17 20:23 UTC, carolyncaron commented on trpcultivate_phenotypes/src/Service/TripalCultivatePhenotypesFileTemplateService.php
> +    $fileheaders = implode($file_delimiter[0], $column_headers) . "\n# DELETE THIS LINE --- START DATA HERE AND USE APPROPRIATE DELIMITER/VALUE SEPARATOR KEY #";
This looks much better :+1: But I would remove the word "KEY" since I think it might be confusing. I think "Use appropriate delimiter/value separator" is clear enough!

```suggestion
    $fileheaders = implode($file_delimiter[0], $column_headers) . "\n# DELETE THIS LINE --- START DATA HERE AND USE APPROPRIATE DELIMITER/VALUE SEPARATOR #";
```

2025-01-20 19:39 UTC, carolyncaron approved these changes
Looks great! 👍

2025-01-20 19:42 UTC, merged